### PR TITLE
add solvers for selected channels and synapses

### PR DESCRIPTION
**Pull request by huangziwei**
Explored some ideas on #38.

Also fixed a bug in #37.

---

I didn't use diffrax because I can't figure out how to use it. @jnsbck if you have time, can you try replacing my custom solvers with diffrax?

### CODE REVIEW

**Comment by jnsbck** [comment]
Will have a look, once I have a bit more time on my hands :)

**Comment by kyralianaka** [comment]
I added the diffrax solver to Ziwei's really nice code -- [https://github.com/jaxleyverse/jaxley-mech/tree/diffrax-solver](https://github.com/jaxleyverse/jaxley-mech/tree/diffrax-solver) -- but my addition could be cleaned up a lot, sorry no time yet. One could also offer different diffrax solvers too. Currently it works for the ribbon synapse with similar results as Ziwei's Newton and unfortunately can't seem to handle dt > 0.05 ish. Hope this is may be helpful :)

**Comment by huangziwei** [comment]
Tried it out a bit, I found that the custom newton is a little bit faster than diffrax newton, and the results seem quite similar by eyeballing. I'm not sure how to compare them systematically, though.

And when dt>0.05, I think it's the `pre_voltage` becomes `nan` after a handful of iterations that breaks both the custom newton and the diffrax newton.

**Comment by huangziwei** [comment]
The `nan` is caused by the Calcium pump in `kuw09`, and it's now fixed by also adding implicit solvers in [4290c6b](https://github.com/jaxleyverse/jaxley-mech/pull/39/commits/4290c6b7a335eb036f21d6ccd2b9a797c558942a).

**Pull request merged**
