### PR TITLE
Mechanism organization

### PR DESCRIPTION
**Pull request by kyralianaka**
Addresses #46 (maybe resolves?)

This pull request includes

- preliminary standardization of mechanism metadata (all lower case, lists for multiple sources, consistent cell type names...)
- added ion type to channel metadata
- wrote functions to view mechanisms by properties (metadata stored in a dataframe that can be filtered)
- updated the readme so that users know how to find the mechanisms they want

Please lmk about any ideas for improvement!

### CODE REVIEW

**Comment by kyralianaka** [comment]
@huangziwei I know you wanted to do a notebook, but maybe we can just do this instead? Both seems a bit overkill

Also, I filter out "notes" from the dataframe -- I think one can expect the user to see these notes if they actually want to use the channel

**Comment by huangziwei** [comment]
maybe add a column for filenames? or we change the filename convention to first name + year so that it will match the reference short name?

**Comment by kyralianaka** [comment]
I changed the file names to first author last name, year like @huangziwei and I talked about, but there are a bunch of channels from different authors in the l5pc file that I'm not sure how best to deal with. They have different authors, so I wouldn't name the file like that, and they come from different types of pyramidal cells, so I'm also not so sure about using that. 

A couple of options would be:
- separating them into different files by paper
- giving them all "layer 5 pyramidal cell" as the cell type and pushing the actual specific cell type to the notes
- something I haven't thought of yet

I am more in favor of separating the channels into different files, but I don't want to make it super inconvenient for those who use them (@michaeldeistler)... what would be your preference?

**Review by michaeldeistler — APPROVED** [review]
That's very useful! Thanks!

**Comment by kyralianaka** [comment]
Ok for now I will just leave the l5pc channels together in that file for legacy purposes. The channels come from about 10 different authors, and one would almost always expect to use the channels together, so I'll leave it as an exception to the naming convention. We can always change it another time.

**Pull request merged**
